name: APK Distribution

on: [push]

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: chs-pro-apks
        path: |
          **/*.apk
        retention-days: 7
